import RPi.GPIO as GPIO
import time 

def main():
    GPIO.setmode(GPIO.BCM)
    a=21
    b=20
    c=16
    d=26
    e=19
    f=13
    g=6
    GPIO.setup(a, GPIO.OUT)
    GPIO.setup(b, GPIO.OUT)
    GPIO.setup(c, GPIO.OUT)
    GPIO.setup(d, GPIO.OUT)
    GPIO.setup(e, GPIO.OUT)
    GPIO.setup(f, GPIO.OUT)
    GPIO.setup(g, GPIO.OUT)
    while True:
        for i in range (16):
            if i ==0:
                GPIO.output(a,1 )
                GPIO.output(b,1 )
                GPIO.output(c,1 )
                GPIO.output(d,1 )
                GPIO.output(e,1 )
                GPIO.output(f,1 )
                GPIO.output(g,0 )
                time.sleep(1)
            elif i==1:
                GPIO.output(a,0 )
                GPIO.output(b,1 )
                GPIO.output(c,1 )
                GPIO.output(d,0 )
                GPIO.output(e,0 )
                GPIO.output(f,0 )
                GPIO.output(g,0 )
                time.sleep(1)
            elif i==2:
                GPIO.output(a,1 )
                GPIO.output(b,1 )
                GPIO.output(c,0 )
                GPIO.output(d,1 )
                GPIO.output(e,1 )
                GPIO.output(f,0 )
                GPIO.output(g,1 )
                time.sleep(1)
            elif i==3:
                GPIO.output(a,1 )
                GPIO.output(b,1 )
                GPIO.output(c,1 )
                GPIO.output(d,1 )
                GPIO.output(e,0 )
                GPIO.output(f,0 )
                GPIO.output(g,1 )
                time.sleep(1)
            elif i==4:
                GPIO.output(a,0 )
                GPIO.output(b,1 )
                GPIO.output(c,1 )
                GPIO.output(d,0 )
                GPIO.output(e,0 )
                GPIO.output(f,1 )
                GPIO.output(g,1 )
                time.sleep(1)
            elif i==5:
                GPIO.output(a,1 )
                GPIO.output(b,0 )
                GPIO.output(c,1 )
                GPIO.output(d,1 )
                GPIO.output(e,0 )
                GPIO.output(f,1 )
                GPIO.output(g,1 )
                time.sleep(1)
            elif i==6:
                GPIO.output(a,1 )
                GPIO.output(b,0 )
                GPIO.output(c,1 )
                GPIO.output(d,1 )
                GPIO.output(e,1 )
                GPIO.output(f,1 )
                GPIO.output(g,1 )
                time.sleep(1)
            elif i==7:
                GPIO.output(a,1 )
                GPIO.output(b,1 )
                GPIO.output(c,1 )
                GPIO.output(d,0 )
                GPIO.output(e,0 )
                GPIO.output(f,0 )
                GPIO.output(g,0 )
                time.sleep(1)
            elif i==8:
                GPIO.output(a,1 )
                GPIO.output(b,1 )
                GPIO.output(c,1 )
                GPIO.output(d,1 )
                GPIO.output(e,1 )
                GPIO.output(f,1 )
                GPIO.output(g,1 )
                time.sleep(1)
            elif i==9:
                GPIO.output(a,1 )
                GPIO.output(b,1 )
                GPIO.output(c,1 )
                GPIO.output(d,1 )
                GPIO.output(e,0 )
                GPIO.output(f,1 )
                GPIO.output(g,1 )
                time.sleep(1)
            elif i==10:#A
                GPIO.output(a,1 )
                GPIO.output(b,1 )
                GPIO.output(c,1 )
                GPIO.output(d,0 )
                GPIO.output(e,1 )
                GPIO.output(f,1 )
                GPIO.output(g,1 )
                time.sleep(1)
            elif i==11:#B
                GPIO.output(a,0 )
                GPIO.output(b,0 )
                GPIO.output(c,1 )
                GPIO.output(d,1 )
                GPIO.output(e,1 )
                GPIO.output(f,1 )
                GPIO.output(g,1 )
                time.sleep(1)
            elif i==12:#C
                GPIO.output(a,1 )
                GPIO.output(b,0 )
                GPIO.output(c,0 )
                GPIO.output(d,1 )
                GPIO.output(e,1 )
                GPIO.output(f,1 )
                GPIO.output(g,0 )
                time.sleep(1)
            elif i==13:#D
                GPIO.output(a,0 )
                GPIO.output(b,1 )
                GPIO.output(c,1 )
                GPIO.output(d,1 )
                GPIO.output(e,1 )
                GPIO.output(f,0 )
                GPIO.output(g,1 )
                time.sleep(1)
            elif i==14:#E
                GPIO.output(a,1 )
                GPIO.output(b,0 )
                GPIO.output(c,0 )
                GPIO.output(d,1 )
                GPIO.output(e,1 )
                GPIO.output(f,1 )
                GPIO.output(g,1 )
                time.sleep(1)
            elif i==15:#F
                GPIO.output(a,1 )
                GPIO.output(b,0 )
                GPIO.output(c,0 )
                GPIO.output(d,0 )
                GPIO.output(e,1 )
                GPIO.output(f,1 )
                GPIO.output(g,1 )
                time.sleep(1)
    
main()
